#!/bin/bash
set -e

if [[ -z $1 ]]; then
	echo "please supply a version name"
    exit 1
fi

version_name=$1
echo "using version name: $version_name"

filename_base="start"
filename_in="$filename_base.c"
path_out="dist_$version_name"
filename_out="$path_out/start"

if [[ -d $path_out ]]; then
rm -r $path_out
fi

mkdir $path_out
mkdir $path_out/data
echo "C adventure, by Willem Siers. Version: $version_name" >> "$path_out/readme.txt"

for f in room*.txt; do
    cp -- "$f" "$path_out/data/${f%.txt}.dat"
done
mv $path_out/data/room_listing.dat $path_out/data/rooms.dat

echo -e "========START========="
echo "input: $filename_in -> output: $filename_out"
echo -e "======================\n$"
if [ ! -d "bin" ]; then
    mkdir bin
    echo done
fi
gcc $filename_in -O3 -o $filename_out -Wall -Wextra -DRelease

#if [[ $? -eq 0 ]]; then
#    ./$filename_out
#fi
exit 0
